### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Dumeowmeow** [sap3d/sap3d#3]
Thank you for your excellent work. I don't understand why the part of Finetuning the diffusion model in 3.2 uses the inaccurate relative pose between the  pictures initialized before to finetune the diffusion, and what is the purpose of this. Also, why use relative pose between pictures? As far as I know, the pose used in zero123 is supposed to be an absolute pose.

**Comment by davidhanx** [comment]
Thanks for your interest!

1. Why we use inaccurate relative pose to finetune diffusion model: 
   A.1: Why we need pose to finetune: Since Zero123 is a pose guided diffusion model, it requires image-pose pair for finetuning.
   A.2: Why we can use inaccurate poses: Although inaccurate, the pose got from stage 1 is generally acceptable and could be optimized to be better during the finetuning process. 

2. Why relative pose:
   A1: Here is an image from zero123 showing how to condition zero123 to generate a novel view image: for a given image, the user would input a relative elevation change and a relative azimuth change to specify the pose change. 
   A2: Referring to appendix A.1 in zero123, the image shows the coordinate system used in zero123~
![image](https://github.com/sap3d/sap3d/assets/86959032/26b130cd-da8d-410c-bba9-65b99e88c6cd)
![image](https://github.com/sap3d/sap3d/assets/86959032/8b84cc04-be13-4e1f-b244-d5096c3ee0bb)

**Comment by Dumeowmeow** [comment]
Thank you for your patient reply!By the way, in the novel perspective, why does the shadow of the object also follow the change?

**Comment by davidhanx** [comment]
1. Ideally for a 3D generation model, it should be able to understand geometry, texture and lightning(interaction with the environment). 
2. Zero123 was trained on rendered images with lighting and shadowing (rendered from objaverse objects). This gives zero123 capability to understand shadow from different views, although this may not be strictly correct.
